spring.cloud.stream:
  function:
    definition: dummy3Processor
  bindings:
    dummy3Processor-in-0:
      destination: dummy2-event
    dummy3Processor-out-0:
      destination: dummy3-event
spring:
  h2:
    console.enabled: true
    console.path: /h2